### ISSUE TITLE
How to call fullcalendar methods?

### ISSUE THREAD

**Issue by frees11** [JavyMB/angular-fullcalendar#22]
Hi, what is proper way to call fullcalendar methods? For example render method or methods to programatically change actual date and so on? I couldn't find it anywhere

**Comment by JavyMB** [comment]
Hi @frees11  You can use  Official Documentation  :) 
https://fullcalendar.io/docs/
Please let me know if you need assistance

**Comment by metachu** [comment]
Your reply above does not explain anything.

Please explain with a code example how to access the fullcalendar render methods.

**Comment by JavyMB** [comment]
I'm aware of fullcalendar.io changes, for now is only supported what you can pass through  calendarOptions, something like:
```
$scope.calendarOptions =  {
                //.. Fullcalendar.js options....  ([read](https://fullcalendar.io/docs/event-object))
header: { center: 'month,agendaWeek' }, // buttons for switching between views

  views: {
    month: { // name of view
      titleFormat: 'YYYY, MM, DD'
      // other view-specific options here
    }
  },
eventRender: function(event, element) {
    // here some functionality https://fullcalendar.io/docs/eventRender
  }
events: function(start, end, timezone, callback) {
    // here some functinality
  }
};
```
```
$scope.events = [
                      {
                          title: 'My Event',
                          start: new Date(),// :) how you can use Date
                          description: 'This is a cool event',
                          color:'#5f6dd0'
                      },
                      {
                          title: 'My Event',
                          start: new moment().add(1,'days'), // :) or MomentJS
                          description: 'This is a cool event',
                          color:'#af6dd0'
                      }
                ];
```
In your directive you pass it 
` <div fc fc-options="calendarOoptions" ng-model="events"   >  </div> `
This is a simple directive, if you want us to add more functionality, please  explain a little bit more your problem

**Comment by The-Mojoo** [comment]
If I want to configure later as **`$('#calendar').fullCalendar('option', 'height', _height);`** ,How can I implement it in angular-fullcalendar? If I reconfigure **`$('#calendar').fullCalendar('option', 'height', _height);`**, the previous configuration will be invalid.
