### ISSUE TITLE
Trying to add a new event dynamically but not added

### ISSUE THREAD

**Issue by jayprajapati857** [JavyMB/angular-fullcalendar#23]
Hello,
I am trying to add an event fetching data from server just fetching the date and time and showing the events on calendar but not able to do it can you help me for this problem

here is the code that i am using i am just adding your function and not doing anything else i a have a events by default created is there 

//defaule events object

$scope.events = [
          {
              title: 'Demo Event',
              start: new moment(),// :) how you can use Date
              description: 'This is a cool event',
              color: '#5f6dd0'
          },
          {
              title: 'My Event',
              start: new moment().add(1, 'days'), // :) or MomentJS
              description: 'This is a cool event',
              color: '#af6dd0'
          }
    ];

for (key in data) {
            console.log(moment(key, "DD/MM/YYYY HH:mm:ss"));
             addEvent();
        } 

var count = 0;
    function addEvent() {
        debugger;
        $scope.events.push({
            title: 'Event ' + count,
            start: new moment(),
            description: 'This is a cool event',
            color: '#5f6dd0'
        });
        count++;
    }

Thanks

**Comment by jayprajapati857** [comment]
here when i am adding events it is added to $scope.events but not rendered into calendar

**Comment by rahulppatidar** [comment]
Hi,
It is working try this:

```
$scope.rpeventss = [

        {
          title  : 'event1',
          start  : new Date()
        },
        {
          title  : 'event2',
          start  : new Date()
         
        },
        {
          title  : 'event3',
          start  : new Date()
        }     

  ];

function addEvent(){

  let newEvent = {
  title: "My New Event",
  start: new moment('2018-08-15')
};
  $scope.rpeventss.push(newEvent);
}

addEvent();
```

**Comment by jayprajapati857** [comment]
yes it is working fine now Thanks
